spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=AdventureWorks2022;encrypt=true;trustServerCertificate=true
    username: sa
    password: Wilbergeneral1.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      validation-timeout: 3000
      connection-timeout: 5000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.hibernate.SQL: DEBUG